### ISSUE TITLE
Weekday Challenge: Unban Dimitris K. (https://dimitris-letter.netlify.app)

### ISSUE THREAD

**Issue by mitsoska** [beginner-codes/challenges#8]
Dimitris K. has expressed his thoughts on this dedicated URL: https://dimitris-letter.netlify.app
Please consider his demands and re-evaluate your decision.

**Comment by ZechCodes** [comment]
This issue is unrelated to this GitHub repository and as such is being closed. Further issues of a similar nature will be reported as spam.
